# Generated by Django 4.2.20 on 2025-03-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('discription', models.TextField(max_length=500)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
