# Generated by Django 4.2.20 on 2025-03-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ratings',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
